### ISSUE TITLE
Can the original BCQ paper be used with a discrete action space?

### ISSUE THREAD

**Issue by VinalAsodia** [sfujim/BCQ#14]
Hi,

I've been reading the original and discretised BCQ papers and wanted to ask if the original BCQ algorithm could be applied to an environment with discrete actions. I'm probably misinterpreting sections on both papers, but to my understanding, the original BCQ algorithm could handle both continuous and discrete actions, whereas the discretised BCQ algorithm focuses solely on discrete actions. I am curious about the VAE in the original paper and wonder if it can be used in a discrete setting. 

Also, I wanted to ask if the "i1/i2" layers in the discretised BCQ network represent the generative model? I'm having some difficulty relating the "i" layers of the BCQ network to Algorithm 1 in the discrete BCQ paper.

I appreciate any help with this query!

**Comment by sfujim** [comment]
There are elements in the original BCQ that could be applied to discrete actions, however the perturbation network update (and concept) really only with continuous actions so some modifications would need to be made. Discrete BCQ aims to handle those issues and simplify the algorithm. 

i1/i2 can be viewed as the generative model. I believe I used "i" at the time, since they also resemble how imitation learning would be done. Thanks for the question.
